name: Deploy to HubSpot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to HubSpot
        uses: HubSpot/hubspot-cms-deploy-action@v1.0
        with:
          src_dir: yuanta-wealth-theme
          dest_dir: yuanta-wealth-theme
          portal_id: "43844850"
          personal_access_key: ${{ secrets.HUBSPOT_ACCESS_KEY }}
